import { AWS_REGION, COGNITO_USER_POOL_ID, COGNITO_CLIENT_ID } from 'react-native-dotenv';

const awsmobile = {
  Auth: {
    region: AWS_REGION,
    userPoolId: COGNITO_USER_POOL_ID,
    userPoolWebClientId: COGNITO_CLIENT_ID
  }
};

// TODO: check which one of the formats do we need.
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// const awsmobile = {
//   "aws_project_region": "eu-west-2",
//   "aws_cognito_identity_pool_id": "eu-west-2:babfd656-ca14-4e71-9862-95eb3b21d715",
//   "aws_cognito_region": "eu-west-2",
//   "aws_user_pools_id": "eu-west-2_CIxYO8aee",
//   "aws_user_pools_web_client_id": "5cictovei72bqr0jiurd85jij6",
//   "oauth": {
//       "domain": "amplifyauth-test-local.auth.eu-west-2.amazoncognito.com",
//       "scope": [
//           "phone",
//           "email",
//           "openid",
//           "profile",
//           "aws.cognito.signin.user.admin"
//       ],
//       "redirectSignIn": "myapp://",
//       "redirectSignOut": "myapp://",
//       "responseType": "code"
//   },
//   "federationTarget": "COGNITO_USER_POOLS"
// };

export default awsmobile;
